show databases;
CREATE DATABASE customers;
use customers;
CREATE TABLE customers (
    customer_id INT,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(50),
    purchase_amount INT,
    location VARCHAR(100),
    size VARCHAR(10),
    color VARCHAR(50),
    season VARCHAR(20),
    review_rating DECIMAL(3,2),
    subscription_status VARCHAR(20),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(20),
    previous_purchases INT,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50),
    age_group VARCHAR(50),
    purchase_frequency_days INT
);


-- what is the total revenue generated by male vs female customers?

select * from customers;

select gender, sum(purchase_amount) as total_revenue 
from customers
group by gender;

-- Which customers used a discount but still spent more than average purchase amount??

select customer_id, purchase_amount
from customers
where discount_applied = 'Yes'
and purchase_amount >= (
      select avg(purchase_amount)
      from customers
      );
-- what are the top 5 products with the highest average review rating??

select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customers
group by item_purchased 
order by avg(review_rating) desc 
limit 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping??

select shipping_type, avg(purchase_amount) 
from customers 
where shipping_type in ("Standard","Express")
group by shipping_type;

-- Do subscribed customers spend more?? compare average spend and total revenue between subcribers and non-subscirbers??

select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_p_amount, round(sum(purchase_amount),2) as sum_p_amount
from customers
group by subscription_status;

-- which 5 products have the highest percentage of purchase with discounts applied??

with total_purchase_amount as (
          select sum(purchase_amount) as total_purchase
          from customers
          where discount_applied = 'Yes'
)

select c.item_purchased, (sum(c.purchase_amount)*100.0/tpa.total_purchase) as total_purchase_percent
from customers as c
cross join total_purchase_amount as tpa
where c.discount_applied = 'Yes'
group by c.item_purchased, tdp.total_purchase
order by total_purchase_percent desc 
limit 5;

-- Segment customers into New, Returning, and Loyal based on their 
-- total number of previous purchases, and show the count
-- of each segment

with customer_type as (
select customer_id, previous_purchases,
case 
   when previous_purchases = 1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
   end as customer_segment
from customers
)

select customer_segment, count(*) as number_of_customers
from customer_type 
group by customer_segment;

-- What are the top 3 most purchased products within each category??

with product_revenue as (
		select category, item_purchased, count(customer_id) as total_orders
		from customers
		group by category, item_purchased
)
select *
from (
select category, item_purchased, total_orders,
row_number() over (partition by category order by total_orders desc ) as rnk 
from product_revenue 
) as x 
where rnk <=3;

-- Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscirbe??

select subscription_status,
count(customer_id) as repeat_buyers 
from customers
where previous_purchases > 5 
group by subscription_status;

-- What is the revenue contribution of each age group??

select age_group,
sum(purchase_amount) as total_revenue 
from customers
group by age_group
order by total_revenue desc;